version: '3.8'

services:
  guacd:
    image: guacamole/guacd
    container_name: guacamole_guacd
    restart: unless-stopped
    networks:
      - guacamole-net

  postgres:
    image: postgres:15
    container_name: guacamole_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      # You should change this password!
      POSTGRES_PASSWORD: SomeChangeMePassword123
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - guacamole-net

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole_web
    restart: unless-stopped
    depends_on:
      - guacd
      - postgres
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      # Use the same password as above
      POSTGRES_PASSWORD: SomeChangeMePassword123
    networks:
      - guacamole-net

volumes:
  postgres-data:

networks:
  guacamole-net:
    driver: bridge
